services:
  web:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
      target: frontend-dev
    image: godploy-frontend-dev
    container_name: godploy-frontend-dev
    volumes:
      - ${HOST_PROJECT_ROOT:-..}/frontend:/app/frontend:cached
      - frontend-node-modules:/app/frontend/node_modules
      - bun-cache:/root/.bun/install/cache
    environment:
      - NODE_ENV=development
      - DEV_BACKEND_URL=http://server:8080
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - godploy-dev
      - traefik_proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.godploy_web.rule=Host(`web.godploy.localhost`)"
        - "traefik.http.routers.godploy_web.entrypoints=websecure"
        - "traefik.http.routers.godploy_web.tls=true"
        - traefik.http.services.godploy_web.loadbalancer.server.port=3000

  server:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
      target: backend-dev
    image: godploy-backend-dev
    container_name: godploy-backend-dev
    volumes:
      - ${HOST_PROJECT_ROOT:-..}/backend:/app/backend:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - godploy-dev-data:/app/backend/data
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    env_file:
      - ../.env
    environment:
      - JWT_SECRET=red_balloon
      - APP_ENV=dev
      - WEB_URL=https://web.godploy.localhost
    ports:
      - "8080:8080"
    working_dir: /app/backend
    restart: unless-stopped
    networks:
      - godploy-dev
      - traefik_proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.godploy_server.rule=Host(`server.godploy.localhost`)"
        - "traefik.http.routers.godploy_server.entrypoints=websecure"
        - "traefik.http.routers.godploy_server.tls=true"
        - traefik.http.services.godploy_server.loadbalancer.server.port=8080

networks:
  godploy-dev:
    driver: overlay
    attachable: true
  traefik_proxy:
    external: true
    name: godploy_traefik_proxy

volumes:
  godploy-dev-data:
    name: godploy-dev-data

  go-build-cache:
    name: godploy-go-build-cache

  go-mod-cache:
    name: godploy-go-mod-cache

  bun-cache:
    name: godploy-bun-cache

  frontend-node-modules:
    name: godploy-frontend-node-modules
