// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package db

import (
	"context"

	"github.com/Roshan-anand/godploy/internal/lib/types"
	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, service_id, name, status)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateDeploymentParams struct {
	ID        uuid.UUID              `json:"id"`
	ServiceID uuid.UUID              `json:"service_id"`
	Name      string                 `json:"name"`
	Status    types.DeploymentStatus `json:"status"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.ServiceID,
		arg.Name,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDeploymentByID = `-- name: DeleteDeploymentByID :exec
DELETE FROM deployments
WHERE id = ?
`

func (q *Queries) DeleteDeploymentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentByID, id)
	return err
}

const getAllDeploymentIdsByServiceID = `-- name: GetAllDeploymentIdsByServiceID :many
SELECT id
FROM deployments
WHERE service_id = ?
`

func (q *Queries) GetAllDeploymentIdsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAllDeploymentIdsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, service_id, name, status, created_at
FROM deployments
WHERE id = ?
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentStatus = `-- name: GetDeploymentStatus :one
SELECT status
FROM deployments
WHERE id = ?
`

func (q *Queries) GetDeploymentStatus(ctx context.Context, id uuid.UUID) (types.DeploymentStatus, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStatus, id)
	var status types.DeploymentStatus
	err := row.Scan(&status)
	return status, err
}

const getDeploymentsByServiceID = `-- name: GetDeploymentsByServiceID :many
SELECT id, service_id, name, status, created_at
FROM deployments
WHERE service_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetDeploymentsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status types.DeploymentStatus `json:"status"`
	ID     uuid.UUID              `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}
