// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createGithubApp = `-- name: CreateGithubApp :exec
INSERT INTO github_app (id, name, organization_id,app_id, pem_key, webhook_secret)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateGithubAppParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	OrganizationID uuid.UUID `json:"organization_id"`
	AppID          int64     `json:"app_id"`
	PemKey         string    `json:"pem_key"`
	WebhookSecret  string    `json:"webhook_secret"`
}

func (q *Queries) CreateGithubApp(ctx context.Context, arg CreateGithubAppParams) error {
	_, err := q.db.ExecContext(ctx, createGithubApp,
		arg.ID,
		arg.Name,
		arg.OrganizationID,
		arg.AppID,
		arg.PemKey,
		arg.WebhookSecret,
	)
	return err
}

const createRedirectSession = `-- name: CreateRedirectSession :exec
INSERT INTO redirect_session (state, user_id, org_id, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateRedirectSessionParams struct {
	State     string    `json:"state"`
	UserID    uuid.UUID `json:"user_id"`
	OrgID     uuid.UUID `json:"org_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRedirectSession(ctx context.Context, arg CreateRedirectSessionParams) error {
	_, err := q.db.ExecContext(ctx, createRedirectSession,
		arg.State,
		arg.UserID,
		arg.OrgID,
		arg.ExpiresAt,
	)
	return err
}

const deleteGithubApp = `-- name: DeleteGithubApp :exec
DELETE FROM github_app
WHERE organization_id = ?
`

func (q *Queries) DeleteGithubApp(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGithubApp, organizationID)
	return err
}

const deleteRedirectSession = `-- name: DeleteRedirectSession :exec
DELETE FROM redirect_session
WHERE state = ?
`

func (q *Queries) DeleteRedirectSession(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteRedirectSession, state)
	return err
}

const getGithubApp = `-- name: GetGithubApp :one
SELECT id, name, organization_id, app_id, installation_id, pem_key, webhook_secret, created_at, updated_at FROM github_app
WHERE organization_id = ?
`

func (q *Queries) GetGithubApp(ctx context.Context, organizationID uuid.UUID) (GithubApp, error) {
	row := q.db.QueryRowContext(ctx, getGithubApp, organizationID)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.AppID,
		&i.InstallationID,
		&i.PemKey,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRedirectSession = `-- name: GetRedirectSession :one
SELECT state, user_id, org_id, expires_at, created_at
FROM redirect_session
WHERE state = ?
`

func (q *Queries) GetRedirectSession(ctx context.Context, state string) (RedirectSession, error) {
	row := q.db.QueryRowContext(ctx, getRedirectSession, state)
	var i RedirectSession
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.OrgID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInstallationID = `-- name: InsertInstallationID :exec
UPDATE github_app
SET installation_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE organization_id = ?
`

type InsertInstallationIDParams struct {
	InstallationID sql.NullInt64 `json:"installation_id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
}

func (q *Queries) InsertInstallationID(ctx context.Context, arg InsertInstallationIDParams) error {
	_, err := q.db.ExecContext(ctx, insertInstallationID, arg.InstallationID, arg.OrganizationID)
	return err
}
