// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCurrentOrg = `-- name: GetCurrentOrg :one
SELECT o.id,o.name 
FROM user u
JOIN organization o ON o.id = u.current_org_id
WHERE u.email = ?
`

type GetCurrentOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetCurrentOrg(ctx context.Context, email string) (GetCurrentOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentOrg, email)
	var i GetCurrentOrgRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
