// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organisation.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const checkOrgExists = `-- name: CheckOrgExists :one
SELECT CAST(EXISTS(
    SELECT 1 FROM organization o
    JOIN user_organization uo ON o.id = uo.organization_id
    WHERE uo.user_email = ? AND o.name = ?
) AS BOOLEAN)
`

type CheckOrgExistsParams struct {
	UserEmail string `json:"user_email"`
	OrgName   string `json:"org_name"`
}

func (q *Queries) CheckOrgExists(ctx context.Context, arg CheckOrgExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkOrgExists, arg.UserEmail, arg.OrgName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUserOrgExists = `-- name: CheckUserOrgExists :one
SELECT CAST(EXISTS(
    SELECT 1 FROM user_organization uo
    WHERE uo.user_email = ? AND uo.organization_id = ?
)AS BOOLEAN)
`

type CheckUserOrgExistsParams struct {
	UserEmail      string    `json:"user_email"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CheckUserOrgExists(ctx context.Context, arg CheckUserOrgExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserOrgExists, arg.UserEmail, arg.OrganizationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserOrgs = `-- name: CountUserOrgs :one
SELECT COUNT(*) FROM organization
`

func (q *Queries) CountUserOrgs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO organization (id, name)
VALUES (?, ?)
RETURNING id, name
`

type CreateOrgParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type CreateOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (CreateOrgRow, error) {
	row := q.db.QueryRowContext(ctx, createOrg, arg.ID, arg.Name)
	var i CreateOrgRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM organization
WHERE id = ?
`

func (q *Queries) DeleteOrg(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrg, id)
	return err
}

const getAllOrg = `-- name: GetAllOrg :many
SELECT o.id,o.name
FROM organization o
JOIN user_organization uo ON o.id = uo.organization_id
WHERE uo.user_email = ?
`

type GetAllOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetAllOrg(ctx context.Context, userEmail string) ([]GetAllOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrg, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrgRow
	for rows.Next() {
		var i GetAllOrgRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentOrg = `-- name: GetCurrentOrg :one
SELECT o.id, o.name
FROM user u
JOIN organization o ON o.id = u.current_org_id
WHERE u.email = ?
`

type GetCurrentOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetCurrentOrg(ctx context.Context, email string) (GetCurrentOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentOrg, email)
	var i GetCurrentOrgRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrgById = `-- name: GetOrgById :one
SELECT id, name FROM organization WHERE id = ?
`

type GetOrgByIdRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetOrgById(ctx context.Context, id uuid.UUID) (GetOrgByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgById, id)
	var i GetOrgByIdRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const linkUserNOrg = `-- name: LinkUserNOrg :exec
INSERT INTO user_organization (user_email, organization_id)
VALUES (?, ?)
`

type LinkUserNOrgParams struct {
	UserEmail      string    `json:"user_email"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) LinkUserNOrg(ctx context.Context, arg LinkUserNOrgParams) error {
	_, err := q.db.ExecContext(ctx, linkUserNOrg, arg.UserEmail, arg.OrganizationID)
	return err
}

const unlinkUserOrg = `-- name: UnlinkUserOrg :exec
DELETE FROM user_organization WHERE user_email = ? AND organization_id = ?
`

type UnlinkUserOrgParams struct {
	UserEmail      string    `json:"user_email"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UnlinkUserOrg(ctx context.Context, arg UnlinkUserOrgParams) error {
	_, err := q.db.ExecContext(ctx, unlinkUserOrg, arg.UserEmail, arg.OrganizationID)
	return err
}
