// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const checkProjectExist = `-- name: CheckProjectExist :one
SELECT CAST(EXISTS(
    SELECT 1
    FROM project p
    JOIN user u ON u.current_org_id = p.organization_id
    WHERE u.email = ? AND p.name = ?
) AS BOOLEAN )
`

type CheckProjectExistParams struct {
	Email       string `json:"email"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) CheckProjectExist(ctx context.Context, arg CheckProjectExistParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectExist, arg.Email, arg.ProjectName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkProjectHasServices = `-- name: CheckProjectHasServices :one
SELECT CAST(EXISTS(
    SELECT 1
    FROM psql_service ps
    WHERE ps.project_id = ?1
    UNION
    SELECT 1
    FROM app_service aps
    WHERE aps.project_id = ?1
) AS BOOLEAN)
`

func (q *Queries) CheckProjectHasServices(ctx context.Context, projectID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectHasServices, projectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (id,name,description,organization_id)
SELECT ?, ?, ?, u.current_org_id
FROM user u
WHERE u.email = ?
LIMIT 1
RETURNING id,name,description
`

type CreateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Email       string    `json:"email"`
}

type CreateProjectRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Email,
	)
	var i CreateProjectRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT p.id,p.name,p.description
FROM project p
JOIN user u ON u.current_org_id = p.organization_id
WHERE u.email = ?
`

type GetAllProjectsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) GetAllProjects(ctx context.Context, email string) ([]GetAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectsRow
	for rows.Next() {
		var i GetAllProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
