// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const checkProjectExist = `-- name: CheckProjectExist :one
SELECT CAST(EXISTS(
    SELECT 1 FROM project p
    JOIN organization o ON o.id = p.organization_id
    WHERE o.id = ?1  AND p.name = ?2
) AS BOOLEAN )
`

type CheckProjectExistParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	ProjectName string    `json:"project_name"`
}

func (q *Queries) CheckProjectExist(ctx context.Context, arg CheckProjectExistParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectExist, arg.OrgID, arg.ProjectName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkProjectHasServices = `-- name: CheckProjectHasServices :one
SELECT CAST(EXISTS (
    SELECT 1 FROM project p
    JOIN psql_service psql ON psql.project_id = p.id
    WHERE p.id = ?
) AS BOOLEAN)
`

func (q *Queries) CheckProjectHasServices(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectHasServices, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (id,name,description,organization_id)
VALUES (?,?,?,?)
RETURNING id,name,description
`

type CreateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	OrgID       uuid.UUID `json:"org_id"`
}

type CreateProjectRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OrgID,
	)
	var i CreateProjectRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT p.id,p.name,p.description
FROM organization o
JOIN project p ON o.id = p.organization_id
WHERE o.id = ?1
`

type GetAllProjectsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) GetAllProjects(ctx context.Context, orgID uuid.UUID) ([]GetAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectsRow
	for rows.Next() {
		var i GetAllProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
