// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/types"
	"github.com/google/uuid"
)

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type PsqlService struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	ServiceID   string    `json:"service_id"`
	Name        string    `json:"name"`
	AppName     string    `json:"app_name"`
	Description string    `json:"description"`
	DbName      string    `json:"db_name"`
	DbUser      string    `json:"db_user"`
	DbPassword  string    `json:"db_password"`
	Image       string    `json:"image"`
	InternalUrl string    `json:"internal_url"`
	CreatedAt   time.Time `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	HashPass  string         `json:"hash_pass"`
	Role      types.UserRole `json:"role"`
	CreatedAt time.Time      `json:"created_at"`
}

type UserOrganization struct {
	UserEmail      string       `json:"user_email"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	JoinedAt       sql.NullTime `json:"joined_at"`
}
