// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/Roshan-anand/godploy/internal/types"
)

type Organization struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	OrganizationID int64     `json:"organization_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Service struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	ProjectID int64     `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	HashPass  string         `json:"hash_pass"`
	Role      types.UserRole `json:"role"`
	CreatedAt time.Time      `json:"created_at"`
}

type UserOrganization struct {
	UserEmail      string       `json:"user_email"`
	OrganizationID int64        `json:"organization_id"`
	JoinedAt       sql.NullTime `json:"joined_at"`
}
