// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Organization struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Project struct {
	ID             int64        `json:"id"`
	Name           string       `json:"name"`
	OrganizationID int64        `json:"organization_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Service struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	ProjectID int64        `json:"project_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	HashPass  string       `json:"hash_pass"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}
