// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organisation.sql

package db

import (
	"context"
)

const insertOrg = `-- name: InsertOrg :one
INSERT INTO organization (name)
VALUES (?)
RETURNING id
`

func (q *Queries) InsertOrg(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertOrg, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
