// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"
)

const checkProjectExist = `-- name: CheckProjectExist :one
SELECT CAST(EXISTS(
    SELECT 1 FROM project p
    JOIN organization o ON o.id = p.organization_id
    WHERE o.id = ?1  AND p.name = ?2
) AS BOOLEAN )
`

type CheckProjectExistParams struct {
	OrgID       int64  `json:"org_id"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) CheckProjectExist(ctx context.Context, arg CheckProjectExistParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectExist, arg.OrgID, arg.ProjectName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO organization (name)
VALUES (?)
RETURNING id
`

func (q *Queries) CreateOrg(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrg, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (name,organization_id)
VALUES (?,?)
RETURNING id,name
`

type CreateProjectParams struct {
	Name           string `json:"name"`
	OrganizationID int64  `json:"organization_id"`
}

type CreateProjectRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.OrganizationID)
	var i CreateProjectRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM organization
WHERE id = ?
`

func (q *Queries) DeleteOrg(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrg, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getAllOrg = `-- name: GetAllOrg :many
SELECT o.id,o.name
FROM organization o
JOIN user_organization uo ON o.id = uo.organization_id
WHERE uo.user_email = ?
`

type GetAllOrgRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetAllOrg(ctx context.Context, userEmail string) ([]GetAllOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrg, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrgRow
	for rows.Next() {
		var i GetAllOrgRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT p.id,p.name
FROM organization o
JOIN project p ON o.id = p.organization_id
WHERE o.id = ?
`

type GetAllProjectsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetAllProjects(ctx context.Context, id int64) ([]GetAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectsRow
	for rows.Next() {
		var i GetAllProjectsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
