// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const checkProjectExist = `-- name: CheckProjectExist :one
SELECT CAST(EXISTS(
    SELECT 1 FROM project p
    JOIN organization o ON o.id = p.organization_id
    WHERE o.id = ?1  AND p.name = ?2
) AS BOOLEAN )
`

type CheckProjectExistParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	ProjectName string    `json:"project_name"`
}

func (q *Queries) CheckProjectExist(ctx context.Context, arg CheckProjectExistParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectExist, arg.OrgID, arg.ProjectName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkProjectHasServices = `-- name: CheckProjectHasServices :one
SELECT CAST(EXISTS (
    SELECT 1 FROM project p
    JOIN psql_service psql ON psql.project_id = p.id
    WHERE p.id = ?
) AS BOOLEAN)
`

func (q *Queries) CheckProjectHasServices(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectHasServices, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO organization (id, name)
VALUES (?, ?)
RETURNING id
`

type CreateOrgParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createOrg, arg.ID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (id,name,organization_id)
VALUES (?,?,?)
RETURNING id,name
`

type CreateProjectParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	OrgID uuid.UUID `json:"org_id"`
}

type CreateProjectRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ID, arg.Name, arg.OrgID)
	var i CreateProjectRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM organization
WHERE id = ?
`

func (q *Queries) DeleteOrg(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrg, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getAllOrg = `-- name: GetAllOrg :many
SELECT o.id,o.name
FROM organization o
JOIN user_organization uo ON o.id = uo.organization_id
WHERE uo.user_email = ?
`

type GetAllOrgRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetAllOrg(ctx context.Context, userEmail string) ([]GetAllOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrg, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrgRow
	for rows.Next() {
		var i GetAllOrgRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT p.id,p.name
FROM organization o
JOIN project p ON o.id = p.organization_id
WHERE o.id = ?1
`

type GetAllProjectsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetAllProjects(ctx context.Context, orgID uuid.UUID) ([]GetAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectsRow
	for rows.Next() {
		var i GetAllProjectsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
