// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relation.sql

package db

import (
	"context"
)

const linkUserNOrg = `-- name: LinkUserNOrg :exec
INSERT INTO user_organization (user_id, organization_id)
VALUES (?, ?)
`

type LinkUserNOrgParams struct {
	UserID         int64 `json:"user_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) LinkUserNOrg(ctx context.Context, arg LinkUserNOrgParams) error {
	_, err := q.db.ExecContext(ctx, linkUserNOrg, arg.UserID, arg.OrganizationID)
	return err
}
