// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPsqlService = `-- name: CreatePsqlService :one
INSERT INTO psql_service (id,project_id,service_id, name, app_name, description, db_name, db_user, db_password, image, internal_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, service_id, name, app_name, description, db_name, db_user, db_password, image, internal_url, created_at
`

type CreatePsqlServiceParams struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	ServiceID   string    `json:"service_id"`
	Name        string    `json:"name"`
	AppName     string    `json:"app_name"`
	Description string    `json:"description"`
	DbName      string    `json:"db_name"`
	DbUser      string    `json:"db_user"`
	DbPassword  string    `json:"db_password"`
	Image       string    `json:"image"`
	InternalUrl string    `json:"internal_url"`
}

func (q *Queries) CreatePsqlService(ctx context.Context, arg CreatePsqlServiceParams) (PsqlService, error) {
	row := q.db.QueryRowContext(ctx, createPsqlService,
		arg.ID,
		arg.ProjectID,
		arg.ServiceID,
		arg.Name,
		arg.AppName,
		arg.Description,
		arg.DbName,
		arg.DbUser,
		arg.DbPassword,
		arg.Image,
		arg.InternalUrl,
	)
	var i PsqlService
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServiceID,
		&i.Name,
		&i.AppName,
		&i.Description,
		&i.DbName,
		&i.DbUser,
		&i.DbPassword,
		&i.Image,
		&i.InternalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deletePsqlService = `-- name: DeletePsqlService :exec
DELETE FROM psql_service
WHERE id = ?
`

func (q *Queries) DeletePsqlService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePsqlService, id)
	return err
}

const getPsqlServiceById = `-- name: GetPsqlServiceById :one
SELECT id, project_id, service_id, name, app_name, description, db_name, db_user, db_password, image, internal_url, created_at
FROM psql_service
WHERE id = ?
`

func (q *Queries) GetPsqlServiceById(ctx context.Context, id uuid.UUID) (PsqlService, error) {
	row := q.db.QueryRowContext(ctx, getPsqlServiceById, id)
	var i PsqlService
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServiceID,
		&i.Name,
		&i.AppName,
		&i.Description,
		&i.DbName,
		&i.DbUser,
		&i.DbPassword,
		&i.Image,
		&i.InternalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const setPsqlServiceId = `-- name: SetPsqlServiceId :exec
UPDATE psql_service
SET service_id = ?
WHERE id = ?
`

type SetPsqlServiceIdParams struct {
	ServiceID string    `json:"service_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetPsqlServiceId(ctx context.Context, arg SetPsqlServiceIdParams) error {
	_, err := q.db.ExecContext(ctx, setPsqlServiceId, arg.ServiceID, arg.ID)
	return err
}
