// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"time"

	"github.com/Roshan-anand/godploy/internal/types"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session (user_id, token, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT u.id,u.email,u.name,u.role,s.expires_at,s.created_at
FROM session s
JOIN user u ON s.user_id = u.id
WHERE s.token = ?
`

type GetSessionByTokenRow struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Role      types.UserRole `json:"role"`
	ExpiresAt time.Time      `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const removeSessionByUID = `-- name: RemoveSessionByUID :exec
DELETE FROM session
WHERE user_id = ?
`

func (q *Queries) RemoveSessionByUID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, removeSessionByUID, userID)
	return err
}
