// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT u.email,s.expires_at,s.created_at
FROM session s
INNER JOIN user u ON s.user_id = u.id
WHERE s.token = ?
`

type GetSessionByTokenRow struct {
	Email     string       `json:"email"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(&i.Email, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO session (user_id, token, expires_at)
VALUES (?, ?, ?)
`

type InsertSessionParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}
