// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/Roshan-anand/godploy/internal/types"
	"github.com/google/uuid"
)

const adminExists = `-- name: AdminExists :one
SELECT CAST(EXISTS (
    SELECT 1 FROM user
    WHERE role = 'admin'
) AS BOOLEAN)
`

func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, adminExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user (id, name, email, hash_pass, role, current_org_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	HashPass     string         `json:"hash_pass"`
	Role         types.UserRole `json:"role"`
	CurrentOrgID uuid.UUID      `json:"current_org_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.HashPass,
		arg.Role,
		arg.CurrentOrgID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
   u.id,
   u.name,
   u.email,
   u.hash_pass,
   u.role,
   u.current_org_id,
   CAST(
    json_group_array(
        json_object('id', o.id, 'name', o.name, 'created_at',  strftime('%Y-%m-%dT%H:%M:%SZ', o.created_at))
    ) AS TEXT
   ) AS orgs
FROM user u
JOIN user_organization uo ON u.email = uo.user_email
JOIN organization o ON uo.organization_id = o.id
WHERE u.email = ?
GROUP BY u.name, u.email, u.hash_pass,u.role
`

type GetUserByEmailRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	HashPass     string         `json:"hash_pass"`
	Role         types.UserRole `json:"role"`
	CurrentOrgID uuid.UUID      `json:"current_org_id"`
	Orgs         string         `json:"orgs"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashPass,
		&i.Role,
		&i.CurrentOrgID,
		&i.Orgs,
	)
	return i, err
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM user
WHERE id = ?
`

func (q *Queries) RemoveUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeUser, id)
	return err
}

const updateCurrentOrg = `-- name: UpdateCurrentOrg :exec
UPDATE user
SET current_org_id = ?
WHERE id = ?
`

type UpdateCurrentOrgParams struct {
	CurrentOrgID uuid.UUID `json:"current_org_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCurrentOrg(ctx context.Context, arg UpdateCurrentOrgParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentOrg, arg.CurrentOrgID, arg.ID)
	return err
}
