// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO user (name, email, hash_pass, role)
VALUES (?, ?, ?, ?)
RETURNING id
`

type AddUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	HashPass string `json:"hash_pass"`
	Role     string `json:"role"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Name,
		arg.Email,
		arg.HashPass,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const adminExists = `-- name: AdminExists :one
SELECT CAST(EXISTS (
    SELECT 1 FROM user
    WHERE role = 'admin'
) AS BOOLEAN)
`

func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, adminExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, hash_pass, role, created_at FROM user
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashPass,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM user
WHERE id = ?
`

func (q *Queries) RemoveUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeUser, id)
	return err
}
